In [115]:
import tensorflow as tf


In [116]:
beta = [tf.constant([1, -2])]
beta

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, -2], dtype=int32)>]

In [159]:
contribution_normalised = [tf.random.uniform(shape=[2, 3, 3,2])]


In [160]:
contribution_normalised_minus_beta = tf.subtract(contribution_normalised, beta)[0]


In [161]:
act_normalised = [contribution_normalised[0][1:]]


In [162]:
act_normalised_minus_beta = tf.math.subtract(act_normalised, beta)[0]


In [164]:
hey = tf.math.divide_no_nan(contribution_normalised_minus_beta, act_normalised_minus_beta)

In [165]:
weighted_output = tf.math.multiply(ratio_con_act, beta)[0]

In [44]:
# weighted_output

In [176]:
contribution = [tf.math.add(contribution_normalised_minus_beta, weighted_output)]
contribution

[<tf.Tensor: shape=(2, 3, 3, 2), dtype=float32, numpy=
 array([[[[ 0.15917087,  0.7743192 ],
          [ 0.53022945,  0.21084118],
          [ 0.72047436,  0.7172216 ]],
 
         [[-0.25011623,  0.46053696],
          [-0.22655487,  0.57217026],
          [ 0.3001511 ,  0.4208355 ]],
 
         [[-0.06744476,  0.71698236],
          [ 0.83643806,  0.1929729 ],
          [-0.22636342,  0.6400838 ]]],
 
 
        [[[ 0.30637014,  0.2018466 ],
          [ 0.40132093,  0.31134534],
          [ 0.42715383,  0.4345088 ]],
 
         [[ 0.5940037 ,  0.560879  ],
          [ 0.61848843,  0.09741569],
          [ 0.3887763 ,  0.6035652 ]],
 
         [[ 0.95291865,  0.23524499],
          [ 0.8874819 ,  0.74677324],
          [ 0.59222615,  0.14091778]]]], dtype=float32)>]